name: macOS Release

on:
  pull_request:
    types: [closed]
    branches: [main] 

permissions:
  contents: write
  packages: write 

jobs:
  build-mac:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest
    env:
      RELEASE_ZIP: Bishop-macOS.zip 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install TinyTOML 
        run: cargo install toml-cli --locked

      - name: Get RELEASE_TAG from Cargo.toml
        id: tag_from_toml
        run: |
          CARGO_TOML=editor/Cargo.toml
          VERSION=$(toml get "$CARGO_TOML" package.version -r)
          TAG="v${VERSION}-mac"
          echo "RELEASE_TAG=${TAG}" >> $GITHUB_ENV
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Run macOS Build
        working-directory: ./editor
        run: cargo make release-editor-mac

      - name: Sign the Bundle
        run: |
          APP_PATH="target/aarch64-apple-darwin/release/bundle/osx/Bishop.app"
          codesign --force --deep --sign - "$APP_PATH"

      - name: Zip Artefact
        id: zip_artifact
        run: |
          APP_DIR="target/aarch64-apple-darwin/release/bundle/osx"
          APP_NAME="Bishop.app"
          ZIP_NAME="${{ env.RELEASE_ZIP }}"
          ditto -c -k --sequesterRsrc --keepParent \
                "${APP_DIR}/${APP_NAME}" \
                "${GITHUB_WORKSPACE}/${ZIP_NAME}"
        shell: bash

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}       
          name: "${{ env.RELEASE_TAG }}"  
          draft: false
          prerelease: true                        
          generate_release_notes: true
          files: ${{ env.RELEASE_ZIP }}
          overwrite_files: true    
          make_latest: true                           
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
